config/routes.rb
Rails.application.routes.draw do
  scope '(/:locale)', locale: /en|ru/ do
    devise_for :users

    resources :users, only: :show do
      resources :connections, except: :index
    end
    
    root "home#index"
  end

  telegram_webhook TelegramWebhooksController
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chat.rb
class Chat < ApplicationRecord
  has_one :connection, dependent: :destroy
end

app/models/connection.rb
class Connection < ApplicationRecord
  class MyValidator < ActiveModel::Validator
    def validate(record)
      record.errors.add :name, 'Need a name starting with X please!' if record.jira_site.start_with? '1'
    end
  end

  belongs_to :user
  belongs_to :chat

  validates :jira_api_token, presence: true
  validates :jira_site, presence: true
  validates :jira_email, presence: true
  validates :chat_id, presence: true
  validates :project_key, presence: true

  validates :chat_id, uniqueness: true

  validates :jira_email, format: { with: URI::MailTo::EMAIL_REGEXP }

  validate :validate_connection

  def validate_connection
    options = {
      username:     jira_email,
      password:     jira_api_token,
      site:         jira_site,
      context_path: '',
      auth_type:    :basic
    }

    client = JIRA::Client.new(options)

    begin
      client.Project.find(project_key)
    rescue JIRA::HTTPError
      errors.add(:base, I18n.t('invalid_jira_connection'))
    rescue StandardError
      errors.add(:base, I18n.t('unknown_jira_connection_error'))
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :connections, dependent: :destroy

  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale

  def after_sign_in_path_for(*)
    user_path(current_user)
  end

  def after_sign_out_path_for(*)
    root_path
  end

  def set_locale
    I18n.locale = extract_locale
  end

  def extract_locale
    I18n.available_locales.include?(params[:locale]&.to_sym) ? params[:locale] : I18n.default_locale
  end

  def default_url_options
    { locale: I18n.locale }
  end
end

app/controllers/connections_controller.rb
class ConnectionsController < ApplicationController
  before_action :set_user
  before_action :set_connection, only: %i[show edit update destroy]
  before_action :set_chats, only: %i[new create edit update]

  # GET /connections/1 or /connections/1.json
  def show; end

  # GET /connections/new
  def new
    @connection = @user.connections.new
  end

  # GET /connections/1/edit
  def edit; end

  # POST /connections or /connections.json
  def create
    @connection = @user.connections.new(connection_params)

    respond_to do |format|
      if @connection.save
        Telegram.bot.send_message(chat_id: @connection.chat_id, text: "#{@connection.user.email} подключил этот чат к проекту #{@connection.project_key}!")
        format.html { redirect_to user_url(@user), notice: 'Connection was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /connections/1 or /connections/1.json
  def update
    respond_to do |format|
      if @connection.update(connection_params)
        format.html { redirect_to user_path(@user), notice: 'Connection was successfully updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    Telegram.bot.send_message(chat_id: @connection.chat_id, text: "#{@connection.user.email} отключил этот чат от проекта #{@connection.project_key}!")
    @connection.destroy
    respond_to do |format|
      format.html { redirect_to user_path(@user), notice: 'Connection was successfully destroyed.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_connection
    @connection = Connection.find(params[:id])
  end

  def set_chats
    @chats = Chat.left_joins(:connection).where(connection: { chat_id: [@connection&.chat_id, nil].uniq })
  end

  def set_user
    @user = User.find(params[:user_id])
  end

  def connection_params
    params.require(:connection).permit(:chat_id, :project_key, :title, :jira_site, :jira_email, :jira_api_token)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/telegram_webhooks_controller.rb
class TelegramWebhooksController < Telegram::Bot::UpdatesController
  def start!(*)
    if payload['chat']['id'].negative?
      start_message = 'Чтобы воспользоваться ботом, зарегистрируйтесь на сайте.'
      respond_with :message, text: start_message, parse_mode: 'Markdown'
    else
      respond_with :message, text: 'Для работы с ботом, добавьте его в групповой чат!'
    end
  end

  def help!(*)
    if payload['chat']['id'].negative?
      help_message = "Чтобы создать задачу на Jira, используя бота, отправьте следующее сообщение:\n\n" \
                     "`@#{Rails.application.credentials.telegram.bot.username || 'BotFather'} <название задачи>\n\n<описание задачи>`"
      respond_with :message, text: help_message, parse_mode: 'Markdown'
    else
      respond_with :message, text: 'Для работы с ботом, добавьте его в групповой чат!'
    end
  end

  def chat!
    if payload['chat']['id'].negative?
      respond_with :message, text: "Chat id: `#{payload['chat']['id']}`", parse_mode: 'Markdown'
    else
      respond_with :message, text: 'Для работы с ботом, добавьте его в групповой чат!'
    end
  end

  def my_chat_member(update)
    case update['new_chat_member']['status']
    when 'member'
      Chat.create!(id: update['chat']['id'], name: update['chat']['title'])
    when 'left'
      Chat.destroy(update['chat']['id'])
    end
  end

  def message(update)
    if update['chat']['id'].negative?
      rename_chat(update['chat']['id'], update['new_chat_title']) if update['new_chat_title']

      return if update['text'].nil?

      return unless update['text'].start_with?('@JoraJiraBot ')

      begin
        response = IssueCreator.call(update)
      rescue IssueCreator::IssueCreationError => e
        response = e.message
      rescue StandardError => e
        puts "#{e.message} (#{e.class})"
        response = "Не удалось создать задачу!\n\nНеизвестная ошибка."
      ensure
        reply_with :message, text: response, parse_mode: 'Markdown'
      end
    else
      reply_with :message, text: 'Для работы с ботом, добавьте его в групповой чат!'
    end
  end

  private

  def rename_chat(chat_id, new_name)
    chat = Chat.find(chat_id)
    chat.update(name: new_name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    if current_user.id == params[:id].to_i
      @user = User.find(params[:id])
    else
      redirect_to user_path(current_user.id)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/connections/_connection.html.slim
div.card.border-dark.md-3 id="#{dom_id connection}"
  .card-header.d-flex.flex-wrap.align-items-center.justify-content-md-between
    p.mb-0
      strong
        =< connection.title 
    div.d-flex
      p.mb-0
        => link_to t('buttons.edit', model_name: Connection.name.downcase), edit_user_connection_path(user_id: @user, id: connection), class: 'btn btn-outline-info'

      p.mb-0
        => link_to '❌', user_connection_path(user_id: @user, id: connection),
                    method: :delete,
                    data: { turbo_method:'delete',
                            turbo_confirm: t('alerts.delete_confirmation') }, class: 'btn btn-outline-danger'
  .card-body
    p
      strong
        = t('connection.chat_id') 
        | :
      =< connection.chat.name
    p 
      strong
        = t('connection.project_key') 
        | :
      =< connection.project_key
    p.mb-0
      strong
        = link_to t('connection.jira_project'), "#{connection.jira_site}jira/software/projects/#{connection.project_key}/issues", class: 'nav-link'

app/views/connections/_form.html.slim
.form-signin.w-50.m-auto
  = form_with model: [ @user, @connection ] do |form|
    - if @connection.errors.any?
      div style="color: red"
        ul
          - @connection.errors.each do |error|
            li = error.full_message
            
    div.field.form-floating
      = form.text_field :title, class: 'form-control', placeholder: "Title"
      = form.label :title, t('connection.title')
    br
    div.field.form-floating
      = form.text_field :project_key, class: 'form-control', placeholder: "Project key"
      = form.label :project_key, t('connection.project_key'), style: "display: block"
    br
    div.field.form-floating
      = form.text_field :jira_site, class: 'form-control', placeholder: "Site"
      = form.label :jira_site, t('connection.jira_site'), style: "display: block"
    br
    div.field.form-floating
      = form.text_field :jira_email, class: 'form-control', placeholder: "jira_email@example.com"
      = form.label :jira_email, t('connection.jira_email'), style: "display: block"
    br
    div.field.form-floating
      = form.text_field :jira_api_token, class: 'form-control', placeholder: "Jira API token"
      = form.label :jira_api_token, t('connection.jira_api_token'), style: "display: block"
    br
    div.field
      = form.label :chat_id, t('connection.chat_id')
      = form.collection_select :chat_id, @chats, :id, :name, {prompt: ''}, {class: 'form-select'}
    br
    div
      = form.submit t('buttons.submit'), class: 'btn-outline-primary w-80 btn btn-lg'

app/views/connections/edit.html.slim
h1
  =< t('titles.edit', model_name: Connection.name.downcase)

br

== render "form", connection: @connection

br

div
  =< link_to t('buttons.back', place: User.name.downcase), user_path(@user), class: 'nav-link'

app/views/connections/new.html.slim
h2.h2
  = t('titles.new', model_name: Connection.name.downcase)

= render "form", connection: @connection

br

div
  = link_to t('titles.home'), user_path(current_user), class: 'nav-link'

app/views/connections/show.html.slim
p style="color: green" = notice

== render @connection

div
  => link_to "Edit this connection", edit_connection_path(@connection), class: 'btn btn-info'
  '|
  =< link_to "Back to connections", connections_path

  = button_to "Destroy this connection", @connection, method: :delete

app/views/home/index.html.slim
div.
  h1.h1
    = t('titles.home') 
  - unless user_signed_in?
    p 
      = link_to t('buttons.login'), new_user_session_path, class: 'btn btn-outline-primary'
    p
      = link_to t('buttons.registration'), new_user_registration_path, class: 'btn btn-outline-primary'
  - else 
    p 
      = button_to t('buttons.exit'), destroy_user_session_path, method: :delete, class: 'btn btn-outline-primary'
    p  
      = link_to t('titles.profile'), user_url(current_user), class: 'btn btn-outline-primary'

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Hefestus Bot
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  body.bg-light.bg-gradient
    .border-bottom
      .container
        header.d-flex.flex-wrap.align-items-center.justify-content-end.justify-content-md-between.py-3
          .text-start.col-md-3.d-flex.align-items-center
            h1.h2.mb-0
              | HEFESTUS BOT
            - if I18n.locale == :ru
              = link_to '🇬🇧', { locale: :en }, class: 'nav-link pb-0'
            - else 
              = link_to '🇷🇺', { locale: :ru }, class: 'nav-link pb-0'
          - if controller_name != 'registrations' && controller_name != 'sessions'
            - unless user_signed_in?
              .col-md-3.text-end 
                = link_to t('buttons.login'), new_user_session_path, class: 'btn btn-outline-primary me-2'
                = link_to t('buttons.registration'), new_user_registration_path, class: 'btn btn-outline-primary'
            - else
              .col-md-3.text-end.d-flex.align-items-center
                p.mx-2.mb-0.fw-semibold
                  = current_user.email 
                = button_to t('buttons.exit'), destroy_user_session_path, method: :delete, class: 'btn btn-outline-primary'
    
    
    .container
      .col-sm-4
        - unless notice.nil?
          br
          p.notice.alert-success.alert
            = notice 
        p.alert 
          = alert


    main.container.text-center
      = yield

app/views/users/show.html.slim
div 
    = link_to t('buttons.new', model_name: Connection.name.downcase), new_user_connection_path(@user), class: 'btn btn-outline-primary'
br
h2
  = t('titles.connections') 
  | :
- if @user.connections.empty?
  = t('titles.empty_connections')
- else
  .row
    .col-sm-4
      = render @user.connections